### ISSUE TITLE
Illegal break statement   at exports.runInThisContext 

### ISSUE THREAD

**Issue by bitboxer** [skibish/hubot-weather#5]
I just tried out the version 1.0.2, sadly I get this on my machine:

```
[Sun Dec 06 2015 12:45:16 GMT+0100 (CET)] ERROR Unable to load /Users/bodo/hubot/node_modules/hubot-weather/src/hubot-weather: SyntaxError: Illegal break statement
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:404:25)
  at Object.loadFile (/Users/bodo/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/Users/bodo/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Robot.loadFile (/Users/bodo/hubot/node_modules/hubot/src/robot.coffee:353:9, <js>:221:20)
  at /Users/bodo/hubot/node_modules/hubot-weather/index.coffee:12:11, <js>:26:33
  at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

**Comment by skibish** [comment]
I will try to fix this today.

Do you exported environment variable which is described in readme.md?

**Comment by bitboxer** [comment]
Yes, and If I remove the if + break it works perfectly.
